### ISSUE TITLE
Daftar terjemahan

### ISSUE THREAD

**Issue by shuLhan** [golang-id/web#1]
Daftar artikel yang direkomendasikan untuk diterjemahkan, diurut berdasarkan
bagian.  Artikel yang sedang dikerjakan oleh seseorang akan diberi label nama akun Github di akhirnya.

##   Memasang Go

* [x] https://golang.org/doc/install/source => /doc/install/source/index.adoc
* [x] https://golang.org/doc/install/gccgo => /doc/install/gccgo/index.adoc

##  Belajar Go

* [x] https://golang.org/doc/effective_go.html => /doc/effective_go.adoc (@shuLhan )
* [x] https://golang.org/doc/diagnostics.html => /doc/diagnostics.adoc (@shuLhan )
* [x] https://golang.org/doc/faq => golang-id.org/doc/faq/index.adoc (@shuLhan )

###  Bahasa

* [x] https://golang.org/blog/json-rpc-tale-of-interfaces => /blog/json-rpc-tale-of-interfaces/index.adoc
* [x] https://golang.org/blog/gos-declaration-syntax => /blog/gos-declaration-syntax/index.adoc
* [x] https://golang.org/blog/defer-panic-and-recover => /blog/defer-panic-and-recover/index.adoc
* [x] https://golang.org/blog/go-concurrency-patterns-timing-out-and => /blog/go-concurrency-patterns-timing-out-and/index.adoc
* [x] https://golang.org/blog/go-slices-usage-and-internals => /blog/go-slices-usage-and-internals/index.adoc
* [x] https://golang.org/blog/gif-decoder-exercise-in-go-interfaces => /blog/gif-decoder-exercise-in-go-interfaces/index.adoc
* [x] https://golang.org/blog/error-handling-and-go => /blog/error-handling-and-go/index.adoc
* [x] https://golang.org/blog/organizing-go-code => /blog/organizing-go-code/index.adoc
* [x] https://blog.golang.org/errors-are-values => /blog/errors-are-values

###  Paket

* [x] https://golang.org/blog/json-and-go => /blog/json-and-go/index.adoc
* [x] https://golang.org/blog/gobs-of-data => /blog/gobs-of-data/index.adoc
* [x] https://golang.org/blog/laws-of-reflection => /blog/laws-of-reflection/index.adoc
* [x] https://golang.org/blog/go-image-package => /blog/go-image-package/index.adoc
* [x] https://golang.org/blog/go-imagedraw-package => /blog/go-imagedraw-package/index.adoc

###  Perkakas

* [x] https://golang.org/doc/articles/go_command.html => doc/articles/go_command.adoc
* [x] https://golang.org/doc/gdb => /doc/gdb/index.adoc
* [x] https://golang.org/doc/articles/race_detector.html => /doc/articles/race_detector.adoc
* [x] https://golang.org/blog/c-go-cgo => /blog/c-go-cgo/index.adoc
* [x] https://golang.org/blog/godoc-documenting-go-code => /blog/godoc-documenting-go-code/index.adoc
* [x] https://golang.org/blog/profiling-go-programs => /blog/profiling-go-programs/index.adoc
* [x] https://golang.org/blog/race-detector => /blog/race-detector/index.adoc

##   Referensi

* [x] https://golang.org/doc/cmd => /doc/cmd/index.adoc
* [x] https://golang.org/ref/spec => /ref/spec/index.adoc
* [x] https://golang.org/cmd/go => /doc/cmd/go/index.adoc
* [x] https://golang.org/ref/mem => /ref/mem/index.adoc

Jika ada permintaan atau membantu menterjemahkan silahkan tambahkan di bagian komentar.

**Comment by gedenata** [comment]
##  Memasang Go
- [ ] https://golang.org/doc/install/source => /doc/install/source/index.adoc https://github.com/golang-id/web/pull/3 (@gedenata)

**Comment by shuLhan** [comment]
@gedenata 

Sebagai klarifikasi, dokumentasi https://golang.org/doc/install itu beda dengan https://golang.org/doc/install/source . Yang pertama itu cara memasang lewat program (yang sudah di-build) yang kedua itu cara pasang dari sumber kode.

Pull-request #3 itu untuk perbaikan dokumentasi yang pertama.

Kalau @gedenata mau terjemahkan yang ke dua kan ya?

**Comment by gedenata** [comment]
> @gedenata
> 
> Sebagai klarifikasi, dokumentasi https://golang.org/doc/install itu beda dengan https://golang.org/doc/install/source . Yang pertama itu cara memasang lewat program (yang sudah di-build) yang kedua itu cara pasang dari sumber kode.
> 
> Pull-request #3 itu untuk perbaikan dokumentasi yang pertama.
> 
> Kalau @gedenata mau terjemahkan yang ke dua kan ya?

@shuLhan Iya mas, ada di next branch saya jadi ada dua route `../install/source` dan `../install/gccgo`, nanti saya refactor lagi.

**Comment by shuLhan** [comment]
Semua artikel yang cukup penting sudah selesai diterjemahkan.
