### ISSUE TITLE
[Help] Install repository

### ISSUE THREAD

**Issue by gedenata** [golang-id/web#2]
`$ mkdir -p $GOPATH/src/github.com/golang-id/web` [Ok]
`$ cd $GOPATH/src/github.com/golang-id/web` [Ok]
`$ git clone https://github.com/golang-id/web .` [Ok]

`$ go generate` [Ok]
`$ export DEBUG=2` [Ok]
`$ ./golangid` [?]

<img width="494" alt="Screen Shot 2020-03-15 at 16 57 13" src="https://user-images.githubusercontent.com/1158185/76698459-15a30700-66de-11ea-9d71-b11cd5a57a66.png">

**Go version**
`go version go1.14 darwin/amd64`

**Go environment**
```bash
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/blockchainzoo/Library/Caches/go-build"
GOENV="/Users/blockchainzoo/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/blockchainzoo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/blockchainzoo/go/src/github.com/golang-id/web/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vy/g05tg4j17r5_qgbn6dywcw0h0000gn/T/go-build461881877=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by shuLhan** [comment]
Sepertinya ada perintah yang tertinggal di bagian README, untuk sementara ada dua cara supaya dapat menjalankan di lokal,

Pertama,

```
$ make serve
```
_atau_,

```
$ go build ./cmd/www-golangid
$ ./www-golangid
```
Kemudian buka http://127.0.0.1:5000 di peramban.

Terima kasih atas laporannya.
